language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install --production=false
script:
  - yarn test
before_deploy: yarn build
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: pecs.jackharvey.io
  local_dir: build
  skip_cleanup: true
  region: eu-west-2
  on:
    branch: master

